module.exports = [{
    name: 'GENERATOR.ACCESSORIES.NOACCESSORIES'
}, {
    name: 'GENERATOR.ACCESSORIES.AFEWACCESSORIES'
}, {
    name: 'GENERATOR.ACCESSORIES.SOMEACCESSORIES'
}, {
    name: 'GENERATOR.ACCESSORIES.LOTSACCESSORIES'
}, {
    name: 'GENERATOR.ACCESSORIES.STREETPEDLAR'
}];