module.exports = [{
    name: {
        MALE: 'GENERATOR.CLOTHINGSTYLE.FASHIONABLE.MALE',
        FEMALE: 'GENERATOR.CLOTHINGSTYLE.FASHIONABLE.FEMALE'
    }
}, {
    name: {
        MALE: 'GENERATOR.CLOTHINGSTYLE.NERDY.MALE',
        FEMALE: 'GENERATOR.CLOTHINGSTYLE.NERDY.FEMALE'
    }
}, {
    name: {
        MALE: 'GENERATOR.CLOTHINGSTYLE.CONSISTENT.MALE',
        FEMALE: 'GENERATOR.CLOTHINGSTYLE.CONSISTENT.FEMALE'
    }
}, {
    name: {
        MALE: 'GENERATOR.CLOTHINGSTYLE.MILITARY.MALE',
        FEMALE: 'GENERATOR.CLOTHINGSTYLE.MILITARY.FEMALE'
    }
}, {
    name: {
        MALE: 'GENERATOR.CLOTHINGSTYLE.UNIFORM.MALE',
        FEMALE: 'GENERATOR.CLOTHINGSTYLE.UNIFORM.FEMALE'
    }
}, {
    name: {
        MALE: 'GENERATOR.CLOTHINGSTYLE.ASSEMBLY.MALE',
        FEMALE: 'GENERATOR.CLOTHINGSTYLE.ASSEMBLY.FEMALE'
    }
}, {
    name: {
        MALE: 'GENERATOR.CLOTHINGSTYLE.SIMPLE.MALE',
        FEMALE: 'GENERATOR.CLOTHINGSTYLE.SIMPLE.FEMALE'
    }
}, {
    name: {
        MALE: 'GENERATOR.CLOTHINGSTYLE.LOADED.MALE',
        FEMALE: 'GENERATOR.CLOTHINGSTYLE.LOADED.FEMALE'
    }
}, {
    name: {
        MALE: 'GENERATOR.CLOTHINGSTYLE.RELIGIOUS.MALE',
        FEMALE: 'GENERATOR.CLOTHINGSTYLE.RELIGIOUS.FEMALE'
    }
}, {
    name: {
        MALE: 'GENERATOR.CLOTHINGSTYLE.HELPFUL.MALE',
        FEMALE: 'GENERATOR.CLOTHINGSTYLE.HELPFUL.FEMALE'
    }
}, {
    name: {
        MALE: 'GENERATOR.CLOTHINGSTYLE.OSTENTATIOUS.MALE',
        FEMALE: 'GENERATOR.CLOTHINGSTYLE.OSTENTATIOUS.FEMALE'
    }
}, {
    name: {
        MALE: 'GENERATOR.CLOTHINGSTYLE.EQUIPPED.MALE',
        FEMALE: 'GENERATOR.CLOTHINGSTYLE.EQUIPPED.FEMALE'
    }
}, {
    name: {
        MALE: 'GENERATOR.CLOTHINGSTYLE.GREEN.MALE',
        FEMALE: 'GENERATOR.CLOTHINGSTYLE.GREEN.FEMALE'
    }
}, {
    name: {
        MALE: 'GENERATOR.CLOTHINGSTYLE.TRANSVERSE.MALE',
        FEMALE: 'GENERATOR.CLOTHINGSTYLE.TRANSVERSE.FEMALE'
    }
}];