module.exports = [{
    "name": {
        "MALE": "GENERATOR.CLOTHES.POORLYDRESSED.MALE",
        "FEMALE": "GENERATOR.CLOTHES.POORLYDRESSED.FEMALE"
    }
}, {
    "name": {
        "MALE": "GENERATOR.CLOTHES.WELLDRESSED.MALE",
        "FEMALE": "GENERATOR.CLOTHES.WELLDRESSED.FEMALE"
    }
}, {
    "name": {
        "MALE": "GENERATOR.CLOTHES.VERYBADLY DRESSED.MALE",
        "FEMALE": "GENERATOR.CLOTHES.VERYBADLY DRESSED.FEMALE"
    }
}, {
    "name": {
        "MALE": "GENERATOR.CLOTHES.VERYWELL DRESSED.MALE",
        "FEMALE": "GENERATOR.CLOTHES.VERYWELL DRESSED.FEMALE"
    }
}, {
    "name": {
        "MALE": "GENERATOR.CLOTHES.NEGLECTED.MALE",
        "FEMALE": "GENERATOR.CLOTHES.NEGLECTED.FEMALE"
    }
}, {
    "name": {
        "MALE": "GENERATOR.CLOTHES.ONHIS 31.MALE",
        "FEMALE": "GENERATOR.CLOTHES.ONHIS 31.FEMALE"
    }
}, {
    "name": {
        "MALE": "GENERATOR.CLOTHES.WORNDIRTY.MALE",
        "FEMALE": "GENERATOR.CLOTHES.WORNDIRTY.FEMALE"
    }
}, {
    "name": {
        "MALE": "GENERATOR.CLOTHES.MAINTAINED.MALE",
        "FEMALE": "GENERATOR.CLOTHES.MAINTAINED.FEMALE"
    }
}];