module.exports = [{
    name: 'GENERATOR.COMBATSTYLE.VERYLONGRANGE'
}, {
    name: 'GENERATOR.COMBATSTYLE.LONGRANGE'
}, {
    name: 'GENERATOR.COMBATSTYLE.CLOSERANGE'
}, {
    name: 'GENERATOR.COMBATSTYLE.CLOSECOMBAT'
}, {
    name: 'GENERATOR.COMBATSTYLE.UNARMED'
}, {
    name: 'GENERATOR.COMBATSTYLE.WRESTLING'
}, {
    name: 'GENERATOR.COMBATSTYLE.SELFDEFENSE'
}];