module.exports = [{
    name: {
        MALE: 'GENERATOR.FAMILIALSITUATION.SINGLE.MALE',
        FEMALE: 'GENERATOR.FAMILIALSITUATION.SINGLE.FEMALE'
    }
}, {
    name: {
        MALE: 'GENERATOR.FAMILIALSITUATION.COHABITING.MALE',
        FEMALE: 'GENERATOR.FAMILIALSITUATION.COHABITING.FEMALE'
    }
}, {
    name: {
        MALE: 'GENERATOR.FAMILIALSITUATION.MARRIED.MALE',
        FEMALE: 'GENERATOR.FAMILIALSITUATION.MARRIED.FEMALE'
    }
}, {
    name: {
        MALE: 'GENERATOR.FAMILIALSITUATION.DIVORCED.MALE',
        FEMALE: 'GENERATOR.FAMILIALSITUATION.DIVORCED.FEMALE'
    }
}, {
    name: {
        MALE: 'GENERATOR.FAMILIALSITUATION.ENGAGED.MALE',
        FEMALE: 'GENERATOR.FAMILIALSITUATION.ENGAGED.FEMALE'
    }
}, {
    name: {
        MALE: 'GENERATOR.FAMILIALSITUATION.WIDOWED.MALE',
        FEMALE: 'GENERATOR.FAMILIALSITUATION.WIDOWED.FEMALE'
    }
}, {
    name: {
        MALE: 'GENERATOR.FAMILIALSITUATION.ONLYCHILD.MALE',
        FEMALE: 'GENERATOR.FAMILIALSITUATION.ONLYCHILD.FEMALE'
    }
}, {
    name: {
        MALE: 'GENERATOR.FAMILIALSITUATION.YOUNGEST.MALE',
        FEMALE: 'GENERATOR.FAMILIALSITUATION.YOUNGEST.FEMALE'
    }
}, {
    name: {
        MALE: 'GENERATOR.FAMILIALSITUATION.OLDERSIBLINGS.MALE',
        FEMALE: 'GENERATOR.FAMILIALSITUATION.OLDERSIBLINGS.FEMALE'
    }
}, {
    name: {
        MALE: 'GENERATOR.FAMILIALSITUATION.HASCHILDREN.MALE',
        FEMALE: 'GENERATOR.FAMILIALSITUATION.HASCHILDREN.FEMALE'
    }
}];