module.exports= [{
    name: {
        MALE: 'GENERATOR.FAMILIALSITUATION.ONLYCHILD.MALE',
        FEMALE: 'GENERATOR.FAMILIALSITUATION.ONLYCHILD.FEMALE'
    }
}, {
    name: {
        MALE: 'GENERATOR.FAMILIALSITUATION.YOUNGEST.MALE',
        FEMALE: 'GENERATOR.FAMILIALSITUATION.YOUNGEST.FEMALE'
    }
}, {
    name: {
        MALE: 'GENERATOR.FAMILIALSITUATION.OLDERSIBLINGS.MALE',
        FEMALE: 'GENERATOR.FAMILIALSITUATION.OLDERSIBLINGS.FEMALE'
    }
}];