module.exports = [{
  "name": {
    "MALE": "GENERATOR.HISTORIC.CHILD_GOOD.MALE",
    "FEMALE": "GENERATOR.HISTORIC.CHILD_GOOD.FEMALE"
  }
}, {
  "name": {
    "MALE": "GENERATOR.HISTORIC.FRIEND_GOOD.MALE",
    "FEMALE": "GENERATOR.HISTORIC.FRIEND_GOOD.FEMALE"
  }
}, {
  "name": {
    "MALE": "GENERATOR.HISTORIC.LOVE_GOOD.MALE",
    "FEMALE": "GENERATOR.HISTORIC.LOVE_GOOD.FEMALE"
  }
}, {
  "name": {
    "MALE": "GENERATOR.HISTORIC.COMP_GOOD.MALE",
    "FEMALE": "GENERATOR.HISTORIC.COMP_GOOD.FEMALE"
  }
}, {
  "name": {
    "MALE": "GENERATOR.HISTORIC.PASSION_GOOD.MALE",
    "FEMALE": "GENERATOR.HISTORIC.PASSION_GOOD.FEMALE"
  }
}, {
  "name": {
    "MALE": "GENERATOR.HISTORIC.SOCIAL_GOOD.MALE",
    "FEMALE": "GENERATOR.HISTORIC.SOCIAL_GOOD.FEMALE"
  }
}, {
  "name": {
    "MALE": "GENERATOR.HISTORIC.FAMILY_GOOD.MALE",
    "FEMALE": "GENERATOR.HISTORIC.FAMILY_GOOD.FEMALE"
  }
}, {
  "name": {
    "MALE": "GENERATOR.HISTORIC.CHILD_BAD.MALE",
    "FEMALE": "GENERATOR.HISTORIC.CHILD_BAD.FEMALE"
  }
}, {
  "name": {
    "MALE": "GENERATOR.HISTORIC.FRIEND_BAD.MALE",
    "FEMALE": "GENERATOR.HISTORIC.FRIEND_BAD.FEMALE"
  }
}, {
  "name": {
    "MALE": "GENERATOR.HISTORIC.LOVE_BAD.MALE",
    "FEMALE": "GENERATOR.HISTORIC.LOVE_BAD.FEMALE"
  }
}, {
  "name": {
    "MALE": "GENERATOR.HISTORIC.COMP_BAD.MALE",
    "FEMALE": "GENERATOR.HISTORIC.COMP_BAD.FEMALE"
  }
}, {
  "name": {
    "MALE": "GENERATOR.HISTORIC.PASSION_BAD.MALE",
    "FEMALE": "GENERATOR.HISTORIC.PASSION_BAD.FEMALE"
  }
}, {
  "name": {
    "MALE": "GENERATOR.HISTORIC.SOCIAL_BAD.MALE",
    "FEMALE": "GENERATOR.HISTORIC.SOCIAL_BAD.FEMALE"
  }
}, {
  "name": {
    "MALE": "GENERATOR.HISTORIC.FAMILY_BAD.MALE",
    "FEMALE": "GENERATOR.HISTORIC.FAMILY_BAD.FEMALE"
  }
}];
