module.exports = [{
    name: {
        MALE: 'GENERATOR.PROFESSION.INNKEEPER.MALE',
        FEMALE: 'GENERATOR.PROFESSION.INNKEEPER.FEMALE'
    }
}, {
    name: {
        MALE: 'GENERATOR.PROFESSION.MERCENARY.MALE',
        FEMALE: 'GENERATOR.PROFESSION.MERCENARY.FEMALE'
    }
}, {
    name: {
        MALE: 'GENERATOR.PROFESSION.THIEF.MALE',
        FEMALE: 'GENERATOR.PROFESSION.THIEF.FEMALE'
    }
}, {
    name: {
        MALE: 'GENERATOR.PROFESSION.MURDERER.MALE',
        FEMALE: 'GENERATOR.PROFESSION.MURDERER.FEMALE'
    }
}, {
    name: {
        MALE: 'GENERATOR.PROFESSION.ENCHANTER.MALE',
        FEMALE: 'GENERATOR.PROFESSION.ENCHANTER.FEMALE'
    }
}, {
    name: {
        MALE: 'GENERATOR.PROFESSION.SPY.MALE',
        FEMALE: 'GENERATOR.PROFESSION.SPY.FEMALE'
    }
}, {
    name: {
        MALE: 'GENERATOR.PROFESSION.GLADIATOR.MALE',
        FEMALE: 'GENERATOR.PROFESSION.GLADIATOR.FEMALE'
    }
}, {
    name: {
        MALE: 'GENERATOR.PROFESSION.HEALER.MALE',
        FEMALE: 'GENERATOR.PROFESSION.HEALER.FEMALE'
    }
}, {
    name: {
        MALE: 'GENERATOR.PROFESSION.DOCTOR.MALE',
        FEMALE: 'GENERATOR.PROFESSION.DOCTOR.FEMALE'
    }
}, {
    name: {
        MALE: 'GENERATOR.PROFESSION.SMITH.MALE',
        FEMALE: 'GENERATOR.PROFESSION.SMITH.FEMALE'
    }
}, {
    name: {
        MALE: 'GENERATOR.PROFESSION.TANNER.MALE',
        FEMALE: 'GENERATOR.PROFESSION.TANNER.FEMALE'
    }
}, {
    name: {
        MALE: 'GENERATOR.PROFESSION.BUTCHER.MALE',
        FEMALE: 'GENERATOR.PROFESSION.BUTCHER.FEMALE'
    }
}, {
    name: {
        MALE: 'GENERATOR.PROFESSION.FARMER.MALE',
        FEMALE: 'GENERATOR.PROFESSION.FARMER.FEMALE'
    }
}, {
    name: {
        MALE: 'GENERATOR.PROFESSION.WISEPERSON.MALE',
        FEMALE: 'GENERATOR.PROFESSION.WISEPERSON.FEMALE'
    }
}, {
    name: {
        MALE: 'GENERATOR.PROFESSION.SOLDIER.MALE',
        FEMALE: 'GENERATOR.PROFESSION.SOLDIER.FEMALE'
    }
}, {
    name: {
        MALE: 'GENERATOR.PROFESSION.SHOEMAKER.MALE',
        FEMALE: 'GENERATOR.PROFESSION.SHOEMAKER.FEMALE'
    }
}, {
    name: {
        MALE: 'GENERATOR.PROFESSION.FURRIER.MALE',
        FEMALE: 'GENERATOR.PROFESSION.FURRIER.FEMALE'
    }
}, {
    name: {
        MALE: 'GENERATOR.PROFESSION.MAIDSERVANT.MALE',
        FEMALE: 'GENERATOR.PROFESSION.MAIDSERVANT.FEMALE'
    }
}, {
    name: {
        MALE: 'GENERATOR.PROFESSION.TAILOR.MALE',
        FEMALE: 'GENERATOR.PROFESSION.TAILOR.FEMALE'
    }
}, {
    name: {
        MALE: 'GENERATOR.PROFESSION.BARBER.MALE',
        FEMALE: 'GENERATOR.PROFESSION.BARBER.FEMALE'
    }
}, {
    name: {
        MALE: 'GENERATOR.PROFESSION.JEWELER.MALE',
        FEMALE: 'GENERATOR.PROFESSION.JEWELER.FEMALE'
    }
}, {
    name: {
        MALE: 'GENERATOR.PROFESSION.RESTAURANTEUR.MALE',
        FEMALE: 'GENERATOR.PROFESSION.RESTAURANTEUR.FEMALE'
    }
}, {
    name: {
        MALE: 'GENERATOR.PROFESSION.OLDCLOTHESDEALER.MALE',
        FEMALE: 'GENERATOR.PROFESSION.OLDCLOTHESDEALER.FEMALE'
    }
}, {
    name: {
        MALE: 'GENERATOR.PROFESSION.PASTRYCOOK.MALE',
        FEMALE: 'GENERATOR.PROFESSION.PASTRYCOOK.FEMALE'
    }
}, {
    name: {
        MALE: 'GENERATOR.PROFESSION.MASON.MALE',
        FEMALE: 'GENERATOR.PROFESSION.MASON.FEMALE'
    }
}, {
    name: {
        MALE: 'GENERATOR.PROFESSION.CARPENTER.MALE',
        FEMALE: 'GENERATOR.PROFESSION.CARPENTER.FEMALE'
    }
}, {
    name: {
        MALE: 'GENERATOR.PROFESSION.WEAVER.MALE',
        FEMALE: 'GENERATOR.PROFESSION.WEAVER.FEMALE'
    }
}, {
    name: {
        MALE: 'GENERATOR.PROFESSION.CHANDLER.MALE',
        FEMALE: 'GENERATOR.PROFESSION.CHANDLER.FEMALE'
    }
}, {
    name: {
        MALE: 'GENERATOR.PROFESSION.MERCER.MALE',
        FEMALE: 'GENERATOR.PROFESSION.MERCER.FEMALE'
    }
}, {
    name: {
        MALE: 'GENERATOR.PROFESSION.COOPER.MALE',
        FEMALE: 'GENERATOR.PROFESSION.COOPER.FEMALE'
    }
}, {
    name: {
        MALE: 'GENERATOR.PROFESSION.BAKER.MALE',
        FEMALE: 'GENERATOR.PROFESSION.BAKER.FEMALE'
    }
}, {
    name: {
        MALE: 'GENERATOR.PROFESSION.WATERCARRIER.MALE',
        FEMALE: 'GENERATOR.PROFESSION.WATERCARRIER.FEMALE'
    }
}, {
    name: {
        MALE: 'GENERATOR.PROFESSION.SCABBARDMAKER.MALE',
        FEMALE: 'GENERATOR.PROFESSION.SCABBARDMAKER.FEMALE'
    }
}, {
    name: {
        MALE: 'GENERATOR.PROFESSION.WINESELLER.MALE',
        FEMALE: 'GENERATOR.PROFESSION.WINESELLER.FEMALE'
    }
}, {
    name: {
        MALE: 'GENERATOR.PROFESSION.HATMAKER.MALE',
        FEMALE: 'GENERATOR.PROFESSION.HATMAKER.FEMALE'
    }
}, {
    name: {
        MALE: 'GENERATOR.PROFESSION.SADDLER.MALE',
        FEMALE: 'GENERATOR.PROFESSION.SADDLER.FEMALE'
    }
}, {
    name: {
        MALE: 'GENERATOR.PROFESSION.CHICKENBUTCHER.MALE',
        FEMALE: 'GENERATOR.PROFESSION.CHICKENBUTCHER.FEMALE'
    }
}, {
    name: {
        MALE: 'GENERATOR.PROFESSION.PURSEMAKER.MALE',
        FEMALE: 'GENERATOR.PROFESSION.PURSEMAKER.FEMALE'
    }
}, {
    name: {
        MALE: 'GENERATOR.PROFESSION.LAUNDRESSE.MALE',
        FEMALE: 'GENERATOR.PROFESSION.LAUNDRESSE.FEMALE'
    }
}, {
    name: {
        MALE: 'GENERATOR.PROFESSION.OILMERCHANT.MALE',
        FEMALE: 'GENERATOR.PROFESSION.OILMERCHANT.FEMALE'
    }
}, {
    name: {
        MALE: 'GENERATOR.PROFESSION.PORTER.MALE',
        FEMALE: 'GENERATOR.PROFESSION.PORTER.FEMALE'
    }
}, {
    name: {
        MALE: 'GENERATOR.PROFESSION.MEATBUTCHER.MALE',
        FEMALE: 'GENERATOR.PROFESSION.MEATBUTCHER.FEMALE'
    }
}, {
    name: {
        MALE: 'GENERATOR.PROFESSION.FISHMERCHANT.MALE',
        FEMALE: 'GENERATOR.PROFESSION.FISHMERCHANT.FEMALE'
    }
}, {
    name: {
        MALE: 'GENERATOR.PROFESSION.BEERSELLER.MALE',
        FEMALE: 'GENERATOR.PROFESSION.BEERSELLER.FEMALE'
    }
}, {
    name: {
        MALE: 'GENERATOR.PROFESSION.BUCKLEMAKER.MALE',
        FEMALE: 'GENERATOR.PROFESSION.BUCKLEMAKER.FEMALE'
    }
}, {
    name: {
        MALE: 'GENERATOR.PROFESSION.PLASTERER.MALE',
        FEMALE: 'GENERATOR.PROFESSION.PLASTERER.FEMALE'
    }
}, {
    name: {
        MALE: 'GENERATOR.PROFESSION.SPICEMERCHANT.MALE',
        FEMALE: 'GENERATOR.PROFESSION.SPICEMERCHANT.FEMALE'
    }
}, {
    name: {
        MALE: 'GENERATOR.PROFESSION.BLACKSMITH.MALE',
        FEMALE: 'GENERATOR.PROFESSION.BLACKSMITH.FEMALE'
    }
}, {
    name: {
        MALE: 'GENERATOR.PROFESSION.PAINTER.MALE',
        FEMALE: 'GENERATOR.PROFESSION.PAINTER.FEMALE'
    }
}, {
    name: {
        MALE: 'GENERATOR.PROFESSION.DOCTOR.MALE',
        FEMALE: 'GENERATOR.PROFESSION.DOCTOR.FEMALE'
    }
}, {
    name: {
        MALE: 'GENERATOR.PROFESSION.ROOFER.MALE',
        FEMALE: 'GENERATOR.PROFESSION.ROOFER.FEMALE'
    }
}, {
    name: {
        MALE: 'GENERATOR.PROFESSION.LOCKSMITH.MALE',
        FEMALE: 'GENERATOR.PROFESSION.LOCKSMITH.FEMALE'
    }
}, {
    name: {
        MALE: 'GENERATOR.PROFESSION.BATHER.MALE',
        FEMALE: 'GENERATOR.PROFESSION.BATHER.FEMALE'
    }
}, {
    name: {
        MALE: 'GENERATOR.PROFESSION.ROPEMAKER.MALE',
        FEMALE: 'GENERATOR.PROFESSION.ROPEMAKER.FEMALE'
    }
}, {
    name: {
        MALE: 'GENERATOR.PROFESSION.INNKEEPER.MALE',
        FEMALE: 'GENERATOR.PROFESSION.INNKEEPER.FEMALE'
    }
}, {
    name: {
        MALE: 'GENERATOR.PROFESSION.TANNER.MALE',
        FEMALE: 'GENERATOR.PROFESSION.TANNER.FEMALE'
    }
}, {
    name: {
        MALE: 'GENERATOR.PROFESSION.COPYIST.MALE',
        FEMALE: 'GENERATOR.PROFESSION.COPYIST.FEMALE'
    }
}, {
    name: {
        MALE: 'GENERATOR.PROFESSION.SCULPTOR.MALE',
        FEMALE: 'GENERATOR.PROFESSION.SCULPTOR.FEMALE'
    }
}, {
    name: {
        MALE: 'GENERATOR.PROFESSION.RUGMAKER.MALE',
        FEMALE: 'GENERATOR.PROFESSION.RUGMAKER.FEMALE'
    }
}, {
    name: {
        MALE: 'GENERATOR.PROFESSION.HARNESSMAKER.MALE',
        FEMALE: 'GENERATOR.PROFESSION.HARNESSMAKER.FEMALE'
    }
}, {
    name: {
        MALE: 'GENERATOR.PROFESSION.BLEACHER.MALE',
        FEMALE: 'GENERATOR.PROFESSION.BLEACHER.FEMALE'
    }
}, {
    name: {
        MALE: 'GENERATOR.PROFESSION.CUTLER.MALE',
        FEMALE: 'GENERATOR.PROFESSION.CUTLER.FEMALE'
    }
}, {
    name: {
        MALE: 'GENERATOR.PROFESSION.GLOVEMAKER.MALE',
        FEMALE: 'GENERATOR.PROFESSION.GLOVEMAKER.FEMALE'
    }
}, {
    name: {
        MALE: 'GENERATOR.PROFESSION.WOOD.MALE',
        FEMALE: 'GENERATOR.PROFESSION.WOOD.FEMALE'
    }
}, {
    name: {
        MALE: 'GENERATOR.PROFESSION.SELLER.MALE',
        FEMALE: 'GENERATOR.PROFESSION.SELLER.FEMALE'
    }
}, {
    name: {
        MALE: 'GENERATOR.PROFESSION.WOODCARVER.MALE',
        FEMALE: 'GENERATOR.PROFESSION.WOODCARVER.FEMALE'
    }
}, {
    name: {
        MALE: 'GENERATOR.PROFESSION.GUARD.MALE',
        FEMALE: 'GENERATOR.PROFESSION.GUARD.FEMALE'
    }
}, {
    name: {
        MALE: 'GENERATOR.PROFESSION.OUTLOW.MALE',
        FEMALE: 'GENERATOR.PROFESSION.OUTLOW.FEMALE'
    }
}, {
    name: {
        MALE: 'GENERATOR.PROFESSION.TRADER.MALE',
        FEMALE: 'GENERATOR.PROFESSION.TRADER.FEMALE'
    }
}, {
    name: {
        MALE: 'GENERATOR.PROFESSION.POLITICIAN.MALE',
        FEMALE: 'GENERATOR.PROFESSION.POLITICIAN.FEMALE'
    }
}, {
    name: {
        MALE: 'GENERATOR.PROFESSION.FARMER.MALE',
        FEMALE: 'GENERATOR.PROFESSION.FARMER.FEMALE'
    }
}, {
    name: {
        MALE: 'GENERATOR.PROFESSION.BREEDER.MALE',
        FEMALE: 'GENERATOR.PROFESSION.BREEDER.FEMALE'
    }
}, {
    name: {
        MALE: 'GENERATOR.PROFESSION.CARRIER.MALE',
        FEMALE: 'GENERATOR.PROFESSION.CARRIER.FEMALE'
    }
}, {
    name: {
        MALE: 'GENERATOR.PROFESSION.NOINFLUENCELORD.MALE',
        FEMALE: 'GENERATOR.PROFESSION.NOINFLUENCELORD.FEMALE'
    }
}, {
    name: {
        MALE: 'GENERATOR.PROFESSION.LORDINFLUENTIAL.MALE',
        FEMALE: 'GENERATOR.PROFESSION.LORDINFLUENTIAL.FEMALE'
    }
}, {
    name: {
        MALE: 'GENERATOR.PROFESSION.LORDCOURTYARD.MALE',
        FEMALE: 'GENERATOR.PROFESSION.LORDCOURTYARD.FEMALE'
    }
}, {
    name: {
        MALE: 'GENERATOR.PROFESSION.KING.MALE',
        FEMALE: 'GENERATOR.PROFESSION.KING.FEMALE'
    }
}, {
    name: {
        MALE: 'GENERATOR.PROFESSION.CONTEUR.MALE',
        FEMALE: 'GENERATOR.PROFESSION.CONTEUR.FEMALE'
    }
}];