module.exports = [{
    name: {
        MALE: 'GENERATOR.REPUTATION.TOTALSTRANGER.MALE',
        FEMALE: 'GENERATOR.REPUTATION.TOTALSTRANGER.FEMALE'
    },
    weight: '0.9'
}, {
    name: {
        MALE: 'GENERATOR.REPUTATION.RUMORS.MALE',
        FEMALE: 'GENERATOR.REPUTATION.RUMORS.FEMALE'
    },
    weight: '0.8'
}, {
    name: {
        MALE: 'GENERATOR.REPUTATION.GOSSIP.MALE',
        FEMALE: 'GENERATOR.REPUTATION.GOSSIP.FEMALE'
    },
    weight: '0.8'
}, {
    name: {
        MALE: 'GENERATOR.REPUTATION.KNOWNINHOMETOWN.MALE',
        FEMALE: 'GENERATOR.REPUTATION.KNOWNINHOMETOWN.FEMALE'
    },
    weight: '0.8'
}, {
    name: {
        MALE: 'GENERATOR.REPUTATION.KNOWNREGION.MALE',
        FEMALE: 'GENERATOR.REPUTATION.KNOWNREGION.FEMALE'
    },
    weight: '0.7'
}, {
    name: {
        MALE: 'GENERATOR.REPUTATION.KNOWNCOUNTRY.MALE',
        FEMALE: 'GENERATOR.REPUTATION.KNOWNCOUNTRY.FEMALE'
    },
    weight: '0.6'
}, {
    name: {
        MALE: 'GENERATOR.REPUTATION.KNOWNLOCALLY.MALE',
        FEMALE: 'GENERATOR.REPUTATION.KNOWNLOCALLY.FEMALE'
    },
    weight: '0.5'
}, {
    name: {
        MALE: 'GENERATOR.REPUTATION.KNOWNREGIONALLY.MALE',
        FEMALE: 'GENERATOR.REPUTATION.KNOWNREGIONALLY.FEMALE'
    },
    weight: '0.4'
}, {
    name: {
        MALE: 'GENERATOR.REPUTATION.NATIONALLYKNOWN.MALE',
        FEMALE: 'GENERATOR.REPUTATION.NATIONALLYKNOWN.FEMALE'
    },
    weight: '0.3'
}, {
    name: {
        MALE: 'GENERATOR.REPUTATION.INTERNATIONALLYKNOWN.MALE',
        FEMALE: 'GENERATOR.REPUTATION.INTERNATIONALLYKNOWN.FEMALE'
    },
    weight: '0.2'
}, {
    name: {
        MALE: 'GENERATOR.REPUTATION.LEGENDARY.MALE',
        FEMALE: 'GENERATOR.REPUTATION.LEGENDARY.FEMALE'
    },
    weight: '0.1'
}, {
    name: {
        MALE: 'GENERATOR.REPUTATION.SCANDALOUS.MALE',
        FEMALE: 'GENERATOR.REPUTATION.SCANDALOUS.FEMALE'
    },
    weight: '0.5'
}, {
    name: {
        MALE: 'GENERATOR.REPUTATION.FEAR.MALE',
        FEMALE: 'GENERATOR.REPUTATION.FEAR.FEMALE'
    },
    weight: '0.5'
}, {
    name: {
        MALE: 'GENERATOR.REPUTATION.DOUBT.MALE',
        FEMALE: 'GENERATOR.REPUTATION.DOUBT.FEMALE'
    },
    weight: '0.5'
}, {
    name: {
        MALE: 'GENERATOR.REPUTATION.HONORABLE.MALE',
        FEMALE: 'GENERATOR.REPUTATION.HONORABLE.FEMALE'
    },
    weight: '0.5'
}, {
    name: {
        MALE: 'GENERATOR.REPUTATION.PRAISEWORTHY.MALE',
        FEMALE: 'GENERATOR.REPUTATION.PRAISEWORTHY.FEMALE'
    },
    weight: '0.5'
}, {
    name: {
        MALE: 'GENERATOR.REPUTATION.ACCUSEDWRONGLY.MALE',
        FEMALE: 'GENERATOR.REPUTATION.ACCUSEDWRONGLY.FEMALE'
    },
    weight: '0.5'
}, {
    name: {
        MALE: 'GENERATOR.REPUTATION.CONFUSESOMEONE.MALE',
        FEMALE: 'GENERATOR.REPUTATION.CONFUSESOMEONE.FEMALE'
    },
    weight: '0.5'
}];