module.exports = [{
    name: {
        MALE: 'GENERATOR.SPECIALSIGN.PROFUSESWEATING.MALE',
        FEMALE: 'GENERATOR.SPECIALSIGN.PROFUSESWEATING.FEMALE'
    }
}, {
    name: {
        MALE: 'GENERATOR.SPECIALSIGN.CLAMMYHANDS.MALE',
        FEMALE: 'GENERATOR.SPECIALSIGN.CLAMMYHANDS.FEMALE'
    }
}, {
    name: {
        MALE: 'GENERATOR.SPECIALSIGN.STRONGBODYODORSMELL.MALE',
        FEMALE: 'GENERATOR.SPECIALSIGN.STRONGBODYODORSMELL.FEMALE'
    }
}, {
    name: {
        MALE: 'GENERATOR.SPECIALSIGN.STRONGBODYODORDIRT.MALE',
        FEMALE: 'GENERATOR.SPECIALSIGN.STRONGBODYODORDIRT.FEMALE'
    }
}, {
    name: {
        MALE: 'GENERATOR.SPECIALSIGN.STRONGBODYODORSWEAT.MALE',
        FEMALE: 'GENERATOR.SPECIALSIGN.STRONGBODYODORSWEAT.FEMALE'
    }
}, {
    name: {
        MALE: 'GENERATOR.SPECIALSIGN.STRONGBODYODORTOBACCO.MALE',
        FEMALE: 'GENERATOR.SPECIALSIGN.STRONGBODYODORTOBACCO.FEMALE'
    }
}, {
    name: {
        MALE: 'GENERATOR.SPECIALSIGN.BADBREATH.MALE',
        FEMALE: 'GENERATOR.SPECIALSIGN.BADBREATH.FEMALE'
    }
}, {
    name: {
        MALE: 'GENERATOR.SPECIALSIGN.HAIRY.MALE',
        FEMALE: 'GENERATOR.SPECIALSIGN.HAIRY.FEMALE'
    }
}, {
    name: {
        MALE: 'GENERATOR.SPECIALSIGN.LARGEBREASTS.MALE',
        FEMALE: 'GENERATOR.SPECIALSIGN.LARGEBREASTS.FEMALE'
    }
}, {
    name: {
        MALE: 'GENERATOR.SPECIALSIGN.ONEHANDED.MALE',
        FEMALE: 'GENERATOR.SPECIALSIGN.ONEHANDED.FEMALE'
    }
}, {
    name: {
        MALE: 'GENERATOR.SPECIALSIGN.WEARAHOOK.MALE',
        FEMALE: 'GENERATOR.SPECIALSIGN.WEARAHOOK.FEMALE'
    }
}, {
    name: {
        MALE: 'GENERATOR.SPECIALSIGN.HUMPBACKED.MALE',
        FEMALE: 'GENERATOR.SPECIALSIGN.HUMPBACKED.FEMALE'
    }
}, {
    name: {
        MALE: 'GENERATOR.SPECIALSIGN.BANDYLEGS.MALE',
        FEMALE: 'GENERATOR.SPECIALSIGN.BANDYLEGS.FEMALE'
    }
}, {
    name: {
        MALE: 'GENERATOR.SPECIALSIGN.CLUBFOOT.MALE',
        FEMALE: 'GENERATOR.SPECIALSIGN.CLUBFOOT.FEMALE'
    }
}, {
    name: {
        MALE: 'GENERATOR.SPECIALSIGN.CUTFINGERS.MALE',
        FEMALE: 'GENERATOR.SPECIALSIGN.CUTFINGERS.FEMALE'
    }
}, {
    name: {
        MALE: 'GENERATOR.SPECIALSIGN.DEAF.MALE',
        FEMALE: 'GENERATOR.SPECIALSIGN.DEAF.FEMALE'
    }
}, {
    name: {
        MALE: 'GENERATOR.SPECIALSIGN.MAKEUP.MALE',
        FEMALE: 'GENERATOR.SPECIALSIGN.MAKEUP.FEMALE'
    }
}, {
    name: {
        MALE: 'GENERATOR.SPECIALSIGN.TATTOO.MALE',
        FEMALE: 'GENERATOR.SPECIALSIGN.TATTOO.FEMALE'
    }
}, {
    name: {
        MALE: 'GENERATOR.SPECIALSIGN.FACIALPARALYSIS.MALE',
        FEMALE: 'GENERATOR.SPECIALSIGN.FACIALPARALYSIS.FEMALE'
    }
}, {
    name: {
        MALE: 'GENERATOR.SPECIALSIGN.PARALYSISOFALIMB.MALE',
        FEMALE: 'GENERATOR.SPECIALSIGN.PARALYSISOFALIMB.FEMALE'
    }
}, {
    name: {
        MALE: 'GENERATOR.SPECIALSIGN.TREMORS.MALE',
        FEMALE: 'GENERATOR.SPECIALSIGN.TREMORS.FEMALE'
    }
}, {
    name: {
        MALE: 'GENERATOR.SPECIALSIGN.SENESCENCE.MALE',
        FEMALE: 'GENERATOR.SPECIALSIGN.SENESCENCE.FEMALE'
    }
}, {
    name: {
        MALE: 'GENERATOR.SPECIALSIGN.PROTRUDINGEARS.MALE',
        FEMALE: 'GENERATOR.SPECIALSIGN.PROTRUDINGEARS.FEMALE'
    }
}, {
    name: {
        MALE: 'GENERATOR.SPECIALSIGN.SICK.MALE',
        FEMALE: 'GENERATOR.SPECIALSIGN.SICK.FEMALE'
    }
}, {
    name: {
        MALE: 'GENERATOR.SPECIALSIGN.TIC.MALE',
        FEMALE: 'GENERATOR.SPECIALSIGN.TIC.FEMALE'
    }
}, {
    name: {
        MALE: 'GENERATOR.SPECIALSIGN.LONGNAILS.MALE',
        FEMALE: 'GENERATOR.SPECIALSIGN.LONGNAILS.FEMALE'
    }
}, {
    name: {
        MALE: 'GENERATOR.SPECIALSIGN.SPITTING.MALE',
        FEMALE: 'GENERATOR.SPECIALSIGN.SPITTING.FEMALE'
    }
}, {
    name: {
        MALE: 'GENERATOR.SPECIALSIGN.UNSIGHTLYWARTS.MALE',
        FEMALE: 'GENERATOR.SPECIALSIGN.UNSIGHTLYWARTS.FEMALE'
    }
}, {
    name: {
        MALE: 'GENERATOR.SPECIALSIGN.WOODENLEG.MALE',
        FEMALE: 'GENERATOR.SPECIALSIGN.WOODENLEG.FEMALE'
    }
}, {
    name: {
        MALE: 'GENERATOR.SPECIALSIGN.NOSERINGS.MALE',
        FEMALE: 'GENERATOR.SPECIALSIGN.NOSERINGS.FEMALE'
    }
}, {
    name: {
        MALE: 'GENERATOR.SPECIALSIGN.EARSPIERCING.MALE',
        FEMALE: 'GENERATOR.SPECIALSIGN.EARSPIERCING.FEMALE'
    }
}, {
    name: {
        MALE: 'GENERATOR.SPECIALSIGN.LIPPIERCING.MALE',
        FEMALE: 'GENERATOR.SPECIALSIGN.LIPPIERCING.FEMALE'
    }
}, {
    name: {
        MALE: 'GENERATOR.SPECIALSIGN.TONGUEPIERCING.MALE',
        FEMALE: 'GENERATOR.SPECIALSIGN.TONGUEPIERCING.FEMALE'
    }
}, {
    name: {
        MALE: 'GENERATOR.SPECIALSIGN.WHISTLES.MALE',
        FEMALE: 'GENERATOR.SPECIALSIGN.WHISTLES.FEMALE'
    }
}, {
    name: {
        MALE: 'GENERATOR.SPECIALSIGN.GIGGLE.MALE',
        FEMALE: 'GENERATOR.SPECIALSIGN.GIGGLE.FEMALE'
    }
}, {
    name: {
        MALE: 'GENERATOR.SPECIALSIGN.SNIFFS.MALE',
        FEMALE: 'GENERATOR.SPECIALSIGN.SNIFFS.FEMALE'
    }
}, {
    name: {
        MALE: 'GENERATOR.SPECIALSIGN.COUGHS.MALE',
        FEMALE: 'GENERATOR.SPECIALSIGN.COUGHS.FEMALE'
    }
}, {
    name: {
        MALE: 'GENERATOR.SPECIALSIGN.SLAMSTONGUE.MALE',
        FEMALE: 'GENERATOR.SPECIALSIGN.SLAMSTONGUE.FEMALE'
    }
}, {
    name: {
        MALE: 'GENERATOR.SPECIALSIGN.SMOOTHSTRAND.MALE',
        FEMALE: 'GENERATOR.SPECIALSIGN.SMOOTHSTRAND.FEMALE'
    }
}, {
    name: {
        MALE: 'GENERATOR.SPECIALSIGN.COMBHAIRS.MALE',
        FEMALE: 'GENERATOR.SPECIALSIGN.COMBHAIRS.FEMALE'
    }
}, {
    name: {
        MALE: 'GENERATOR.SPECIALSIGN.SPITS.MALE',
        FEMALE: 'GENERATOR.SPECIALSIGN.SPITS.FEMALE'
    }
}, {
    name: {
        MALE: 'GENERATOR.SPECIALSIGN.CLEARSTHROAT.MALE',
        FEMALE: 'GENERATOR.SPECIALSIGN.CLEARSTHROAT.FEMALE'
    }
}, {
    name: {
        MALE: 'GENERATOR.SPECIALSIGN.SCRATCHINGBODY.MALE',
        FEMALE: 'GENERATOR.SPECIALSIGN.SCRATCHINGBODY.FEMALE'
    }
}, {
    name: {
        MALE: 'GENERATOR.SPECIALSIGN.PERFORMSRITUAL.MALE',
        FEMALE: 'GENERATOR.SPECIALSIGN.PERFORMSRITUAL.FEMALE'
    }
}, {
    name: {
        MALE: 'GENERATOR.SPECIALSIGN.RECITEDPSALM.MALE',
        FEMALE: 'GENERATOR.SPECIALSIGN.RECITEDPSALM.FEMALE'
    }
}, {
    name: {
        MALE: 'GENERATOR.SPECIALSIGN.PRAY.MALE',
        FEMALE: 'GENERATOR.SPECIALSIGN.PRAY.FEMALE'
    }
}, {
    name: {
        MALE: 'GENERATOR.SPECIALSIGN.STRIKESCHEST.MALE',
        FEMALE: 'GENERATOR.SPECIALSIGN.STRIKESCHEST.FEMALE'
    }
}, {
    name: {
        MALE: 'GENERATOR.SPECIALSIGN.PLAYINGCOIN.MALE',
        FEMALE: 'GENERATOR.SPECIALSIGN.PLAYINGCOIN.FEMALE'
    }
}, {
    name: {
        MALE: 'GENERATOR.SPECIALSIGN.PLAYINGDAGGER.MALE',
        FEMALE: 'GENERATOR.SPECIALSIGN.PLAYINGDAGGER.FEMALE'
    }
}, {
    name: {
        MALE: 'GENERATOR.SPECIALSIGN.PLAYINGBALL.MALE',
        FEMALE: 'GENERATOR.SPECIALSIGN.PLAYINGBALL.FEMALE'
    }
}, {
    name: {
        MALE: 'GENERATOR.SPECIALSIGN.PLAYINGCARDS.MALE',
        FEMALE: 'GENERATOR.SPECIALSIGN.PLAYINGCARDS.FEMALE'
    }
}, {
    name: {
        MALE: 'GENERATOR.SPECIALSIGN.PLAYINGPENDANT.MALE',
        FEMALE: 'GENERATOR.SPECIALSIGN.PLAYINGPENDANT.FEMALE'
    }
}, {
    name: {
        MALE: 'GENERATOR.SPECIALSIGN.SWEAR.MALE',
        FEMALE: 'GENERATOR.SPECIALSIGN.SWEAR.FEMALE'
    }
}, {
    name: {
        MALE: 'GENERATOR.SPECIALSIGN.HUMS.MALE',
        FEMALE: 'GENERATOR.SPECIALSIGN.HUMS.FEMALE'
    }
}, {
    name: {
        MALE: 'GENERATOR.SPECIALSIGN.MOISTENSLIPS.MALE',
        FEMALE: 'GENERATOR.SPECIALSIGN.MOISTENSLIPS.FEMALE'
    }
}, {
    name: {
        MALE: 'GENERATOR.SPECIALSIGN.STOMP.MALE',
        FEMALE: 'GENERATOR.SPECIALSIGN.STOMP.FEMALE'
    }
}, {
    name: {
        MALE: 'GENERATOR.SPECIALSIGN.BLINK.MALE',
        FEMALE: 'GENERATOR.SPECIALSIGN.BLINK.FEMALE'
    }
}, {
    name: {
        MALE: 'GENERATOR.SPECIALSIGN.FLITS.MALE',
        FEMALE: 'GENERATOR.SPECIALSIGN.FLITS.FEMALE'
    }
}, {
    name: {
        MALE: 'GENERATOR.SPECIALSIGN.CROSSESARMS.MALE',
        FEMALE: 'GENERATOR.SPECIALSIGN.CROSSESARMS.FEMALE'
    }
}, {
    name: {
        MALE: 'GENERATOR.SPECIALSIGN.HELDCHIN.MALE',
        FEMALE: 'GENERATOR.SPECIALSIGN.HELDCHIN.FEMALE'
    }
}, {
    name: {
        MALE: 'GENERATOR.SPECIALSIGN.FANSONESELF.MALE',
        FEMALE: 'GENERATOR.SPECIALSIGN.FANSONESELF.FEMALE'
    }
}, {
    name: {
        MALE: 'GENERATOR.SPECIALSIGN.INFLAMEDGESTURES.MALE',
        FEMALE: 'GENERATOR.SPECIALSIGN.INFLAMEDGESTURES.FEMALE'
    }
}, {
    name: {
        MALE: 'GENERATOR.SPECIALSIGN.SPEAKHANDS.MALE',
        FEMALE: 'GENERATOR.SPECIALSIGN.SPEAKHANDS.FEMALE'
    }
}, {
    name: {
        MALE: 'GENERATOR.SPECIALSIGN.FLUIDGESTURES.MALE',
        FEMALE: 'GENERATOR.SPECIALSIGN.FLUIDGESTURES.FEMALE'
    }
}, {
    name: {
        MALE: 'GENERATOR.SPECIALSIGN.DOUBTFULPOUT.MALE',
        FEMALE: 'GENERATOR.SPECIALSIGN.DOUBTFULPOUT.FEMALE'
    }
}, {
    name: {
        MALE: 'GENERATOR.SPECIALSIGN.GRIN.MALE',
        FEMALE: 'GENERATOR.SPECIALSIGN.GRIN.FEMALE'
    }
}, {
    name: {
        MALE: 'GENERATOR.SPECIALSIGN.GIGGLE.MALE',
        FEMALE: 'GENERATOR.SPECIALSIGN.GIGGLE.FEMALE'
    }
}, {
    name: {
        MALE: 'GENERATOR.SPECIALSIGN.GNAWSNAILS.MALE',
        FEMALE: 'GENERATOR.SPECIALSIGN.GNAWSNAILS.FEMALE'
    }
}, {
    name: {
        MALE: 'GENERATOR.SPECIALSIGN.PICKINGTEETH.MALE',
        FEMALE: 'GENERATOR.SPECIALSIGN.PICKINGTEETH.FEMALE'
    }
}, {
    name: {
        MALE: 'GENERATOR.SPECIALSIGN.DRINK.MALE',
        FEMALE: 'GENERATOR.SPECIALSIGN.DRINK.FEMALE'
    }
}, {
    name: {
        MALE: 'GENERATOR.SPECIALSIGN.SMOKEOFTEN.MALE',
        FEMALE: 'GENERATOR.SPECIALSIGN.SMOKEOFTEN.FEMALE'
    }
}, {
    name: {
        MALE: 'GENERATOR.SPECIALSIGN.DEPENDENTDRUG.MALE',
        FEMALE: 'GENERATOR.SPECIALSIGN.DEPENDENTDRUG.FEMALE'
    }
}];