module.exports = [{
    "name": "GENERATOR.TALENTS.PRETTYFLEXIBLE"
}, {
    "name": "GENERATOR.TALENTS.ALREADYREAD IT"
}, {
    "name": "GENERATOR.TALENTS.VENIVIDIVICI"
}, {
    "name": "GENERATOR.TALENTS.NOTSEENNOTTAKEN"
}, {
    "name": "GENERATOR.TALENTS.NOTEVENAFRAID"
}, {
    "name": "GENERATOR.TALENTS.SEENSOMEONE"
}, {
    "name": "GENERATOR.TALENTS.IKNOWAGUY"
}, {
    "name": "GENERATOR.TALENTS.CALLAFRIEND"
}, {
    "name": "GENERATOR.TALENTS.KNOWEACHOTHER"
}, {
    "name": "GENERATOR.TALENTS.FUSS"
}, {
    "name": "GENERATOR.TALENTS.MINEISBIGGER"
}, {
    "name": "GENERATOR.TALENTS.THATMINE"
}, {
    "name": "GENERATOR.TALENTS.RAISEDHEAVIER"
}, {
    "name": "GENERATOR.TALENTS.SPACEHERE"
}, {
    "name": "GENERATOR.TALENTS.IUNDERSTANDQUICK"
}, {
    "name": "GENERATOR.TALENTS.THROUGHHERE"
}, {
    "name": "GENERATOR.TALENTS.GUARDIANANGEL"
}, {
    "name": "GENERATOR.TALENTS.RHYTHM"
}];